<a href="https://colab.research.google.com/github/GuiAbade/AluraAtividades/blob/main/Criando_um_banco_de_dados_local.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlalchemy

In [2]:
from sqlalchemy import create_engine, MetaData, Table, inspect

In [3]:
engine = create_engine('sqlite:///:memory:')

In [4]:
url ='https://raw.githubusercontent.com/alura-cursos/Pandas/refs/heads/main/clientes_banco.csv'

In [5]:
import pandas as pd

In [6]:
dados = pd.read_csv(url)

In [8]:
dados.head()

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008808,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio
4,5008809,52,Ensino médio,Solteiro,1,Associado comercial,Vendas,8,270000.0,0,Casa/apartamento próprio

In [16]:
dados.to_sql('clientes', engine, index=False, if_exists='replace')

438463

In [17]:
inspector = inspect(engine)

In [18]:
print(inspector.get_table_names())

['clientes']

In [32]:
query = 'SELECT * FROM clientes WHERE Categoria_de_renda="Empregado" '

In [33]:
empregados = pd.read_sql(query, engine)

In [34]:
empregados.head()

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008806,58,Ensino médio,Casado,2,Empregado,Segurança,3,112500.0,1,Casa/apartamento próprio
3,5008815,46,Ensino superior,Casado,2,Empregado,Contabilidade,2,270000.0,1,Casa/apartamento próprio
4,5112956,46,Ensino superior,Casado,2,Empregado,Contabilidade,2,270000.0,1,Casa/apartamento próprio

In [39]:
empregados.to_sql('empregados', con=engine, index=False, if_exists='replace')

226059

In [31]:
pd.read_sql_table('empregados', engine)

,ID_Cliente,Idade,Grau_escolaridade,Estado_civil,Tamanho_familia,Categoria_de_renda,Ocupacao,Anos_empregado,Rendimento_anual,Tem_carro,Moradia
0,5008804,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
1,5008805,32,Ensino superior,União-estável,2,Empregado,Outro,12,427500.0,1,Apartamento alugado
2,5008834,30,Ensino médio,Solteiro,2,Empregado,Outro,4,112500.0,0,Casa/apartamento próprio
3,5008835,30,Ensino médio,Solteiro,2,Empregado,Outro,4,112500.0,0,Casa/apartamento próprio
4,6153712,30,Ensino médio,Solteiro,2,Empregado,Outro,4,112500.0,0,Casa/apartamento próprio
...,...,...,...,...,...,...,...,...,...,...,...
35876,6835980,41,Ensino superior incompleto,Casado,2,Empregado,Outro,14,135000.0,1,Casa/apartamento próprio
35877,6835981,41,Ensino superior incompleto,Casado,2,Empregado,Outro,14,135000.0,1,Casa/apartamento próprio
35878,6835982,41,Ensino superior incompleto,Casado,2,Empregado,Outro,14,135000.0,1,Casa/apartamento próprio
35879,6837905,43,Ensino médio,Casado,3,Empregado,Outro,7,355050.0,1,Casa/apartamento próprio
35880,6837906,43,Ensino médio,Casado,3,Empregado,Outro,7,355050.0,1,Casa/apartamento próprio

In [40]:
pd.read_sql_table('empregados', engine, columns=['ID_Cliente', 'Grau_escolaridade', 'Rendimento_anual'])

        ID_Cliente Grau_escolaridade  Rendimento_anual
0          5008804   Ensino superior          427500.0
1          5008805   Ensino superior          427500.0
2          5008806      Ensino médio          112500.0
3          5008815   Ensino superior          270000.0
4          5112956   Ensino superior          270000.0
...            ...               ...               ...
226054     6837905      Ensino médio          355050.0
226055     6837906      Ensino médio          355050.0
226056     6839936      Ensino médio          135000.0
226057     6840222      Ensino médio          103500.0
226058     6842885      Ensino médio          121500.0

[226059 rows x 3 columns]